### PR TITLE
Add example projects

### PR DESCRIPTION
**Pull request by sbonami**
We should provide example projects with various implementations, including:
- Basic Example
- [MagicalRecord](https://github.com/magicalpanda/MagicalRecord)
- ~~[ObjectiveRecord](https://github.com/mneorr/ObjectiveRecord)~~

Other potential implementations:
- [SSDataKit](https://github.com/soffes/SSDataKit)?
- [mogenerator](https://github.com/rentzsch/mogenerator)?

### CODE REVIEW

**Comment by sbonami** [comment]
Hey Yuan, I've made progress on a local branch for both a Basic and a MagicalRecord Example project. Like you, I've run into a UI hang. I'm in the process of debugging, however it looks like [another incremental store](https://github.com/magicalpanda/MagicalRecord/issues/556) has the same issue with no solution provided. I have a workaround to the issue, but nothing I'd consider a solution. I'll keep you posted.

**Comment by hokster7** [comment]
I've tried to run with the MagicalRecord example as well but also got the UI hang (unsurprisingly). Any news on this?

**Comment by liangjun-jiang** [comment]
@fanyuanheng , if you look at your managedObjectContext set up, 

```
_managedObjectContext = [[NSManagedObjectContext alloc] initWithConcurrencyType:NSMainQueueConcurrencyType];

```

if your setup is `_managedObjectContext = [[NSManagedObjectContext alloc] init];`
you will see UI Hang . Changed to the code above, it will be fine for the UI Hang.

Also refer issue #30

**Comment by Alydyn** [comment]
I'm pretty sure this initializes the context with `NSConfinementConcurrencyType`.  Per my comment in issue #30 I think that you could use `NSPrivateQueueConcurrencyType` as long as there is no `parentContext`.

**Comment by Alydyn** [comment]
Another comment on this, try creating your private contexts with no parent contexts and see if you still get the UI hang.

**Comment by sbonami** [comment]
@loftyet is correct, using an `NSMainQueueConcurrencyType` will work for now, however to directly answer your question @fatuhoku, I have no news or progress to share. I've bumped AFIncrementalStore's issue as well to see if anyone in that community has fixed the bug.

**Comment by liangjun-jiang** [comment]
@sbonami , good work on PFIncrementalStore. I have tested it for three different Coredata projects. So far, the project with one model works quite well. Projects with more than one model is problematic, and not consistent. If you need a demo project, I can send a pull request.

**Comment by sbonami** [comment]
In short, please do! PFIncrementalStore started as a pod to be used in a few projects. Now that I have time to work on those projects, better testing of PFIS can commence! I'm going to be jumping back on development of this project, and better usage/examples, soon!

**Comment by Alydyn** [comment]
Yeah, really sorry @sbonami, I keep meaning to get back to testing PFIS but am struggling to find time!  Hoping schedule clears up later this month after my project deadline.

**Comment by sbonami** [comment]
@Alydyn @fatuhoku @fanyuanheng: I've (hopefully) fixed the NSPrivateConcurrencyQueueType issue, and subsequently the MagicalRecord example now works as expected. I'm going to merge this and test a few things, then will push an update to cocoapods if all works as planned.

**Pull request merged**
